##
# CAS Server Context Configuration
#
server:
  context-path: /cas
  port: 8443
  ssl:
    key-store: classpath:jbonekeystore
    key-store-password: 123456
    key-password: 123456
  tomcat:
    max-http-post-size: 2097152
    basedir: build/tomcat
    max-threads: 10
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8

cas:
  authn:
    shiro:
      requiredRoles: sso
      location: classpath:shiro.ini
    pm:
      enabled: true
      #policyPattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d){8,10}
      reset:
        text: Reset your password with this link %s
        subject: Password Reset Request
        from: jbone666@163.com
        expirationMinutes: 1
        emailAttribute: mail
        securityQuestionsEnabled: true
        autoLogin: false
  server:
    name: https://jbone-cas.majunwei.com:8443
    prefix: https://jbone-cas.majunwei.com:8443/cas
  adminPagesSecurity:
    ip: 127.0.0.1
    actuatorEndpointsEnabled: true
  monitor:
    endpoints:
      dashboard:
        enabled: true
        sensitive: true
  #使用json加载注册到CAS上的服务，还可以使用redis／rest等方式
  serviceRegistry:
    initFromJson: false
    jpa:
      healthQuery: select now()
      isolateInternalQueries: false
      url: jdbc:mysql://121.42.174.77:3306/jbone_cas?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
      failFastTimeout: 1
      dialect: org.hibernate.dialect.MySQL5Dialect
      leakThreshold: 10
      jpaLockingTgtEnabled: true
      batchSize: 1
      user: jbone_cas
      ddlAuto: none
      password: Jbone_cas_666
      autocommit: false
      driverClass: com.mysql.jdbc.Driver
      idleTimeout: 5000
      dataSourceName:
      dataSourceProxy: false
      properties.hibernate.hbm2ddl.auto: none
      properties.hibernate.show_sql: true
      pool.suspension: false
      pool.minSize: 6
      pool.maxSize: 18
      pool.maxWait: 2000

  #票据持久化，用于分布式管理用户票据
  ticket:
    registry:
      jpa:
        ticketLockType: NONE
        jpaLockingTimeout: 3600
        healthQuery: select now()
        isolateInternalQueries: false
        url: jdbc:mysql://121.42.174.77:3306/jbone_cas?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        failFastTimeout: 1
        dialect: org.hibernate.dialect.MySQL5Dialect
        leakThreshold: 10
        jpaLockingTgtEnabled: true
        batchSize: 1
        defaultCatalog:
        defaultSchema: jbone_cas
        user: jbone_cas
        ddlAuto: update
        password: Jbone_cas_666
        autocommit: false
        driverClass: com.mysql.jdbc.Driver
        idleTimeout: 5000
        dataSourceName:
        dataSourceProxy: false

        # Hibernate-specific properties (i.e. `hibernate.globally_quoted_identifiers`)
        properties.hibernate.hbm2ddl.auto: update
        properties.hibernate.show_sql: true

        pool.suspension: false
        pool.minSize: 6
        pool.maxSize: 18
        pool.maxWait: 2000

        crypto.signing.key:
        crypto.signing.keySize: 512
        crypto.encryption.key:
        crypto.encryption.keySize: 16
        crypto.alg: AES
        crypto.enabled: false
    tgt:
      # 启用rememberMe
      rememberMe:
        enabled: true
        timeToKillInSeconds: 28800
      # tgt有效期（会话超时时间）
      timeout:
        maxTimeToLiveInSeconds: 28800
    st:
      maxLength: 20
      # ST使用次数
      numberOfUses: 1
      # ST有效期60S
      timeToKillInSeconds: 60
  #单点登出
  slo:
    disabled: false
    asynchronous: true
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force  : true
  cloud:
    bus:
      enabled: false
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: Jbone-CAS
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
  mail:
    host: smtp.163.com
    ##port: 25
    username: jbone666@163.com
    password: jbonesq2018
    testConnection: true
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

management:
  security.enabled: false
  context-path: /status
  server.ssl.enabled: false

security.basic.enabled: false

logging:
  config: classpath:log4j2.xml

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
    metadata-map:
      user.name: jbone
      user.password: jbone
    healthcheck.enabled: true
  instance:
    prefer-ip-address: true
    instance-id: http://${spring.cloud.client.ipAddress}:${server.port}
    statusPageUrl: ${cas.server.prefix}/status/info
    healthCheckUrl: ${cas.server.prefix}/status/health
    homePageUrl: ${cas.server.prefix}/
    metadata-map:
      management.context-path: /status
ribbon:
    ConnectTimeout: 500
    ReadTimeout: 3000
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

jbone.rpc.sysServer.feign:
  protocol: http
  name: jbone-sys-server

# 不允许静态用户
staticAuthentication: false

